apiVersion: v1
kind: Secret
metadata:
  name: loki-s3
  namespace: netobserv
stringData:
  access_key_id: minioadmin
  access_key_secret: miniopassword
  bucketnames: loki-data
  endpoint: http://minio-svc.minio-storage.svc:9000
  region: eu-central-1
